### ISSUE TITLE
Where can I found source for serial1 library?

### ISSUE THREAD

**Issue by achest** [perdidor/Arduino-MDB-UART#2]
Hello!

/home/.../Arduino-MDB-UART/MDB_UART_Master/MDB_UART_Master.ino: In function 'void EXT_UART_Setup()':
MDB_UART_Master:75:3: error: 'Serial1' was not declared in this scope
   Serial1.begin(9600);

I need source Code for Serial1 class. Where can i found it? 

ESP8266 /Wemos. Probably I need other lib than for arduino. 

Many thanks,

Bestregards,

achest

**Comment by perdidor** [comment]
Hello.
Your board has only one hardware UART (as per datasheet) called Serial0 (or just Serial). You can try software UART library like this: https://github.com/plerup/espsoftwareserial
