### ISSUE TITLE
Communication via USB

### ISSUE THREAD

**Issue by lvlisael** [perdidor/Arduino-MDB-UART#3]
Is it possible to avoid the DB9 part using Serial1 to communicate with the mdb device and Serial0 (usb serial) to com with PC?

**Comment by lvlisael** [comment]
I think it is possible, but still getting a error on the coin changer ("Check Vendor Disabled by machine)

**Comment by perdidor** [comment]
There are two ways to deliver data to master PC using USB:
1. Not changing implemented PCB design. Use USB-UART (FT232 or CP210x based) adapter and connect it to rx/tx/gnd socket in the bottom of the board
2. Change PCB design: remove MAX232 chip and DB9M connector, place FT232-like chip (only SMD design available afaik) and USB connector.
