### ISSUE TITLE
Enabling bill acceptor

### ISSUE THREAD

**Issue by edgarborja** [perdidor/Arduino-MDB-UART#5]
Hi @perdidor , thanks for your work and for making this project available.

I was able to get the 1280p talking to a bill acceptor:

![image](https://user-images.githubusercontent.com/15452062/48751078-222d6180-ec48-11e8-9d75-7816232e03bc.png)

But I am unable to initialize it, I have been reading the MDB protocol specs but it is a hard read.

Can you please post an example of what I need to type in the SEND box to enable the acceptor?

**Comment by perdidor** [comment]
Hello. As per MDB 4.2 datasheet, "On power-up or reset all bill acceptance and escrow are disabled". So, you have to manually enable bill accepting. Try to send this command through test software:
34ffff000032
34 - address byte
ffff - enable accepting all bill types
0000 - disable escrow feature on all bill types
32 - MDB checksum
read please section 6-10 of MDB datasheet included in repo (file MDB_version_4-2.pdf).
Cheers.

**Comment by perdidor** [comment]
Text file with command examples added to repository.
https://github.com/perdidor/Arduino-MDB-UART/blob/master/cmd_examples.txt

**Comment by edgarborja** [comment]
Thank you! This was the missing link.
