### ISSUE TITLE
How to make connections?

### ISSUE THREAD

**Issue by ertankucukoglu** [perdidor/Arduino-MDB-UART#6]
Hello,

Thanks for sharing your work. It is indeed valuable. I am trying to make MDB-RS232 communication. I have not worked with MDB protocol or vending machines before. Now, I must learn how to do that. I am still waiting vending machine parts to be delivered myself for my internal testings. I do not know what brand and model of a machine I need to work, yet.

My very much newbie questions are:
1- Do I need arduino to use your card? I cannot be sure by looking at information available. I cannot see clearly from the video. However, github name implies this is for arduino and there are some arduino codes, too.
2- I do not see any code for atmega1284 itself. Some people said to me "it is a programmable one. I need to have my code and upload that on that chip itself." I want to say that I am no electronic or electrician at all. I just want to be clarify that chip itself need to be programmed or not.
3- So far, I could not find any AtMEGA1284P-PU chip in my region. I can buy ATMEGA1284P-AU chip. Is that "AU" suffix chip can be used for that project?

Thanks & regards,
Ertan

**Comment by perdidor** [comment]
1. Arduino is common name for evaluation boards, based on variable 8bit AtMega chips. Also, it's a whole ecosystem, including IDE for software developing and fast growing community (see arduino.org). So, do not think at this stage, just do what written in readme EXACTLY.
2. Code for AtMega1284 located in file MDB_UART_Master.ino . Open it within Arduino IDE and you'll see source text. Programming "bare" chip is not so simple as programming Arduino board with USB connector, but you'll have to do it. Just google for "arduino nano as ISP", "atmega1284 bare upload". And yes, you'll need Arduino Nano V3 board for this. You can find ISP connector on board (MOSI, MISO, SCK, RESET, GND)
3. Atmega1284P-PU selected for this project as it has DIP (through-hole) design, as whole board components. All of Atmega chips having 2 or more hardware UARTs will work identical, regardless of chip package design, so you can use any.
