### ISSUE TITLE
Min controller flash memory size

### ISSUE THREAD

**Issue by ertankucukoglu** [perdidor/Arduino-MDB-UART#7]
Hello,

What is minimum memory requirement for that setup? Used controller seemingly have 128kB flash memory.

Even that project is a low cost one. I am trying to figure a solution for a lower cost requirement project. Thinking of reducing memory on controller to get down its price. I read software uart is not suggested where timing is important.

Thanks & regards,
Ertan

**Comment by perdidor** [comment]
Hello.
Compiled firmware is 5256 bytes, RAM required 618 bytes. It’s not so much the amount of memory on board as there are at least two hardware UART ports. As well as convenient chip packaging. The chip was chosen for the project on the basis of these parameters. You can choose any other chip with 2 or more hardware UARTs to upload this firmware.
Cheers.
